variable "vpc_id" {}
variable "asg_private_subnet" {}
variable "elb_public_subnet" {}
variable "db_private_subnet" {}
variable "instance_type" {}
variable "asg_security_group" {}
variable "min_size" {}
variable "max_size" {}
variable "availability_zone_names" {}
variable "elb_security_group" {}
variable "instance_class" {}
variable "db_username" {}
variable "db_password" {}
